# Generated by Django 3.1.2 on 2020-10-24 21:05

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaigns',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('campaign_name', models.CharField(max_length=100)),
                ('campaign_description', models.TextField(default='No Description')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignSendRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('request_name', models.CharField(max_length=100)),
                ('template', models.TextField()),
                ('subject', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('email_user', models.CharField(max_length=200)),
                ('mails_send', models.BooleanField(default=False)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.campaigns')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='UsersDirectory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user_email', models.CharField(max_length=250)),
                ('is_subscribed', models.BooleanField(default=False)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignUserResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('userResponses', models.JSONField()),
                ('counter', models.IntegerField(default=0)),
                ('campaign_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.campaignsendrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usersdirectory')),
            ],
        ),
    ]
