# Generated by Django 3.1.2 on 2020-10-25 01:34

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignsendrequest',
            name='tags',
        ),
        migrations.AddField(
            model_name='campaignsendrequest',
            name='tag',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=[], size=None),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='usersdirectory',
            name='tags',
        ),
        migrations.AddField(
            model_name='usersdirectory',
            name='tag',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=[], size=None),
            preserve_default=False,
        ),
    ]
